### PR TITLE
Add "news" to the list of tracked changelog names

### PR DESCRIPTION
**Pull request by mattmenefee**
This partially addresses #44.

### CODE REVIEW

**Comment by mattmenefee** [comment]
I did a quick scan of the test suite and didn't think I saw anything that needs to be updated there. Let me know if that's not the case. Thanks!

**Comment by MaximeD** [comment]
> I did a quick scan of the test suite and didn't think I saw anything that needs to be updated there
Indeed there is no testing of all recognized names :)

**Comment by MaximeD** [comment]
Your changes have been pushed to ruby gems, and will be available as soon as you update it. Thank you very much for this!

**Comment by mattmenefee** [comment]
:+1:

**Pull request merged**
