### PR TITLE
Add automatically generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

And special for such cases - I created a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** (and split them to separate lists according labels) from :octocat: GitHub Issue Tracker.

By using this script your Change Log will look like this: [Click me!](https://github.com/skywinder/gem_updater/blob/add-change-log-file/CHANGELOG.md)

> ***What’s the point of a change log?***
To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
> :copyright: *[http://keepachangelog.com](http://keepachangelog.com/)*

And now you do not need to spend a lot of :hourglass_flowing_sand: for filling it manually!

Some essential features of **github_changelog_generator**:

- Generate **neat** Change Log file according basic [change log guidelines](http://keepachangelog.com). :gem:

- **Distinguish** issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )  :scissors:

- You can set which labels should be included/excluded and apply a lot of other customisations, to fit changelog for your personal style :tophat: (*look `github_changelog_generator --help`  for details)*

You can easily update this file in future by simply run script: `github_changelog_generator MaximeD/gem_updater` in your repo folder and it make your Change Log file up-to-date again!

Since now you do not have to fill your `CHANGELOG.md` manually: just run script, relax and take a cup of :coffee: before your next release!

Hope you find this commit as useful. :wink:

### CODE REVIEW

**Comment by MaximeD** [comment]
Hello @skywinder, thank you for your suggestion. Unfortunately this won't fit my needs : I don't want my `changelog.md` to be automatically generated.

As far as I am concerned, a `changelog` is a documentation tool for users, and users won't care about which issues were closed, or which pull requests were accepted. This is important from the developer's point of view, but not for users of a project.
There are also things you do in your codebase which are of no interest for your users. For example, why would I include in my changelog that I fix a typo in the readme ? This is not a regression, not an enhancement, nothing that would change whatever in the life of my users, nothing of interest that should be part of a `changelog` (while this should still go through the regular process of a pull request).
So definitely, as a good changelog is for humans it should be written by humans. Though I hope you could help enforcing good practices. An automatic changelog is still better than no changelog at all.


As a last note, please consider you have quite an aggressive and spam like way of presenting your code. I understand the will for visibility, but please do as every one: spread the word on internet (that is specialized websites and such) and hope for others to get interest. What you do is sending pull requests to every trending repo to do add stuff which is not related to their codebase. I am glad for you, some accepted, and happily most github users are nice folks ready to send you words of encouragement. But still what you do is spamming. While this remains more interesting than selling viagra to us, this remains spamming, that is unsolicited advertising for your software. And we all wish github to remain a clear place of development.


Oh yes and there is a bug in your automatically generated email ;) :

> By using this script your Change Log will look like this: [Click me!](https://github.com/skywinder/user_project/blob/add-change-log-file/CHANGELOG.md)

When a project already has a `changelog.md` what you generate is `changelog_auto.md` and link is not pointing to new file.

**Comment by skywinder** [comment]
@MaximeD thank you for your very desriptive feedback.
Just want to mention some things about:

>  This is important from the developer's point of view, but not for users of a project.

You are placed your code on GitHub. And it's mostly developers platform, not users, so it's make sense.

> For example, why would I include in my changelog that I fix a typo in the readme?

It's only about correct labeling of issues. Set a proper label (`wontfix` for example,from pre-defined, or your own) - it's not a big deal to maintain auto-changelog. And it will be excluded from the list.

>As a last note, please consider you have quite an aggressive and spam like way of presenting your code.

Ok, I get it. Sorry, that it annoys you. 
Usually I receive only positive feedbacks, and I was sure that it makes GitHub community better. Since yours is the second negative feedback (2-nd from 30, although) - I will reconsider my quite aggressive PR politics. Thank you.
In my defence I just want to mention, that  I not push commits to any repo. I select repo, which are well-tagged and labeled (ok, yours has only 1 enhancement  label, but, as you mention - auto-changelog is better then nothing) and it's look very nice in your repo.

> Oh yes and there is a bug in your automatically generated email ;) :

Thanks :) I fixed it. :wink: But, I thinks I don't continue using it, since it considered as spam by some users. And it's definitely not, that I want...

**Comment by oelmekki** [comment]
Hi @skywinder , you may consider making a [Show
HN](https://news.ycombinator.com/show) on Hacker News (be sure to read
the guideline if you're not used to HN first). This very project was
launched that way this week-end, and it was quite efficient.

Other channels you may consider : 

- writing a protip about it on coderwall
- tweeting with `#rails #ruby` hashtag
- showing it the discussion ML / plateform of your local area

**Comment by skywinder** [comment]
@oelmekki Simply **wow**! Just a single twit works like insane! Thanks a lot for suggestion!

**Comment by oelmekki** [comment]
You're welcome :)

**Pull request closed without merging**
